[[capnproto]]
arch = "i686"
git-tree-sha1 = "e4cd57816863264515b2a038c8d8b97cfb7c1363"
libc = "musl"
os = "linux"

    [[capnproto.download]]
    sha256 = "e28a7debd05df8427e01f6097d601042a0e45ce9b8d7343158bcfdc1701e281b"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.i686-linux-musl.tar.gz"
[[capnproto]]
arch = "aarch64"
git-tree-sha1 = "06ed642218320e2913994bad4c307e9d347f02e2"
libc = "musl"
os = "linux"

    [[capnproto.download]]
    sha256 = "22661899c5ca28e0801d83e728bb03245217f8a7f84d50883c2dd7f96cb940ad"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.aarch64-linux-musl.tar.gz"
[[capnproto]]
arch = "i686"
git-tree-sha1 = "633db7f52fa7fe1f744e985ed635f61232b044ab"
os = "windows"

    [[capnproto.download]]
    sha256 = "b8a2e31957ab9d7e3515ad89de849f4f1b476a326748bc95c2f3d8730c74ac96"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.i686-w64-mingw32.tar.gz"
[[capnproto]]
arch = "x86_64"
git-tree-sha1 = "c521fba09abcec8c4460bb9aebcce9d4845d3324"
os = "windows"

    [[capnproto.download]]
    sha256 = "193aa6080d10714ad3e705d0cdae7fedddb1055db8d2e12ebaaea5e2d5ea400e"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.x86_64-w64-mingw32.tar.gz"
[[capnproto]]
arch = "armv7l"
git-tree-sha1 = "ce40749ebf2d0a7e75c1e5168e21959411be8d18"
libc = "glibc"
os = "linux"

    [[capnproto.download]]
    sha256 = "56f36aa04e976b16bb8519dea80c95a4a7ee2fe136867b8320cfe073607b524f"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.armv7l-linux-gnueabihf.tar.gz"
[[capnproto]]
arch = "armv7l"
git-tree-sha1 = "4ebe45fe98a45e3ee7c9be41aab4bb1aa47984b4"
libc = "musl"
os = "linux"

    [[capnproto.download]]
    sha256 = "aa78c9074788386517c38b8edac8dcf80afda2121199fe4ccc3637d50c9abf93"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.armv7l-linux-musleabihf.tar.gz"
[[capnproto]]
arch = "i686"
git-tree-sha1 = "82e12d097827956ce5807e227086ee115ce74a41"
libc = "glibc"
os = "linux"

    [[capnproto.download]]
    sha256 = "b8e03ef1bd13cb5b0c36f60736cb4db77885ef5b57a67f0b28027e81f0cc5546"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.i686-linux-gnu.tar.gz"
[[capnproto]]
arch = "x86_64"
git-tree-sha1 = "7ccad40eed5c2667a772729db5d53707449f27ae"
libc = "glibc"
os = "linux"

    [[capnproto.download]]
    sha256 = "c817b0a658e2f9f4e0be440766a4348664f5bbaba8f46d4ada960566745f3126"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.x86_64-linux-gnu.tar.gz"
[[capnproto]]
arch = "powerpc64le"
git-tree-sha1 = "28e2eb6c64b56fccb49a1ac33646ce12a93f3054"
libc = "glibc"
os = "linux"

    [[capnproto.download]]
    sha256 = "cb0dd4a3c52fd32f6ebdd45e8b18df32e6dcd5cabe9f6028e54ef141058cea55"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.powerpc64le-linux-gnu.tar.gz"
[[capnproto]]
arch = "x86_64"
git-tree-sha1 = "e582871eef2ce2001a33c6a6bf16007805a4f464"
os = "macos"

    [[capnproto.download]]
    sha256 = "cc0d7c5e79d91dfdee447531de7b4c6f7264efdb11255806bdf87aba2f242df7"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.x86_64-apple-darwin14.tar.gz"
[[capnproto]]
arch = "aarch64"
git-tree-sha1 = "a9dee40083c039d8843f740b8061bded3777cf89"
libc = "glibc"
os = "linux"

    [[capnproto.download]]
    sha256 = "5affca46be5e86ff75c562a5baa834ebd7b8a5a657ed80c9a3fb4bcdcd80c4f2"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.aarch64-linux-gnu.tar.gz"
[[capnproto]]
arch = "x86_64"
git-tree-sha1 = "1c61fd6b4362e7f0af5112ee8e7e4eeae751a688"
os = "freebsd"

    [[capnproto.download]]
    sha256 = "a19dfe0af70a856d8481a8bbf80dd4e61da419d2634a6f8db24454619bd71f83"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.x86_64-unknown-freebsd11.1.tar.gz"
[[capnproto]]
arch = "x86_64"
git-tree-sha1 = "f96374c3444912c5109de375c1edee1bba2a0511"
libc = "musl"
os = "linux"

    [[capnproto.download]]
    sha256 = "13187b58c37b4de264c8584e5f0c565178e74ddabf5837e247900cfca28b63f1"
    url = "https://github.com/JuliaBinaryWrappers/capnproto_jll.jl/releases/download/capnproto-v0.7.0+1/capnproto.v0.7.0.x86_64-linux-musl.tar.gz"
