# Autogenerated wrapper script for capnproto_jll for x86_64-linux-musl
export capnp, libcapnp

JLLWrappers.@generate_wrapper_header("capnproto")
JLLWrappers.@declare_library_product(libcapnp, "libcapnp-0.8.0.so")
JLLWrappers.@declare_executable_product(capnp)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcapnp,
        "lib/libcapnp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        capnp,
        "bin/capnp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
